export enum DATE_FORMATS {
  ISO_DATE = 'AAAA-MM-DDTHH:MM:SS.mmmZ',
  DAY_MONTH_4DIGITS_YEAR = 'dd/MM/yyyy',
  DAY_MONTH_4DIGITS_YEAR_24SYSTEM_HOUR_MINUTES = 'dd/MM/yyyy HH:mm',
  DAY_MONTH_4DIGITS_YEAR_AT_24SYSTEM_HOUR_MINUTES = "dd/MM/yyyy à's' HH:mm",
}
